version: 0.0
os: linux
files:
  - source: /
    destination: /var/app/current
permissions:
  - object: /var/app/current
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start-app.sh
      timeout: 300
      runas: root
