version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing dependencies"

artifacts:
  files:
    - app.js
    - package.json
    - appspec.yml
    - scripts/install-dependencies.sh
    - scripts/start-app.sh
